[package]
name = "checkr-sale-abi"
version = "0.0.0"
authors = [ "Checkr token",]
edition = "2021"
publish = false

[dependencies.checkr-sale]
path = ".."

[dependencies.elrond-wasm]
version = "0.18.2"

[dependencies.elrond-wasm-debug]
version = "0.18.2"
